import Head from 'next/head'
import LeadingPartners from '@/Components/LeadingPartners'
import NavbarBusiness from '@/Components/NavbarBusiness'
import BannerBusiness from '@/Components/BannerBusiness'
import ServicesBusiness from '@/Components/ServicesBusiness'
import OfferingBusiness from '@/Components/OfferingBusiness'
import TestimonialBusiness from '@/Components/TestimonialBusiness'
import SecurityBusiness from '@/Components/SecurityBusiness'
import FooterBusiness from '@/Components/FooterBusiness'
import { useState } from 'react'

function Business() {

  const [current, setCurrent] = useState('nye_cards');

  return (
    <>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="style.css" rel="stylesheet"/>
      </Head>
      <NavbarBusiness current={current} setCurrent={setCurrent}/>
    <BannerBusiness/>
     <LeadingPartners/>
     <ServicesBusiness current={current}/>
     <OfferingBusiness/>
  <TestimonialBusiness/> 
<SecurityBusiness/>
   <FooterBusiness/>
    </>
  )
}

export default Business;