import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "@/Components/Navbar";
import Banner from "@/Components/Banner";
import Services from "@/Components/Services";
import Offering from "@/Components/Offering";
import Testimonial from "@/Components/Testimonial";
import Security from "@/Components/Security";
import LeadingPartners from "@/Components/LeadingPartners";
import Footer from "@/Components/Footer";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [current, setCurrent] = useState("nye_cards");
  return (
    <>
      <Head>
        <title>Rapipay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar current={current} setCurrent={setCurrent} />
        <Banner />
        <LeadingPartners />
        <Services current={current} />
        <Offering />
        <Testimonial />
        <Security />
        <Footer />
      </main>
    </>
  );
}
